[package]
name = "tradr-oidc"
version.workspace = true
edition.workspace = true
license.workspace = true
publish.workspace = true

[dependencies]
reqwest = { version = "0.12", default-features = false, features = ["rustls-tls"] }
tradr-core = { path = "../tradr-core" }
sha2 = "0.10"
base64 = "0.22"
serde_json = "1"

[dev-dependencies]
tokio = { version = "1", features = ["macros", "rt-multi-thread"] }
